import { Link } from 'react-router-dom';
import AppShell from '../../components/AppShell/AppShell';
import RepoStats from '../../components/RepoStats/RepoStats';
import Btn from '../../components/Button/Button';
import Group from '../../components/ButtonGroup/ButtonGroup';
import Input from '../../components/Input/Input';
import Select from '../../components/Select/Select';
import Checkbox from '../../components/Checkbox/Checkbox';
import Radio, { RadioGroup } from '../../components/Radio/Radio';
import Card, { CardHeader, CardTitle, CardBody, CardFooter } from '../../components/Card/Card';
import { Notice } from '../../components/Toast/Toast';
import { useRepo, formatCount } from '../../lib/useRepo';
import styles from './Introduction.module.css';

const featured = [
  { to: '/colors/palettes', category: 'Foundations', title: 'Color', body: 'Cyan brand accent, Zinc neutrals, functional state scales.' },
  { to: '/typography/font-family', category: 'Foundations', title: 'Typography', body: 'Geist + Geist Mono — variable woff2, OFL-1.1, bundled.' },
  { to: '/components/button', category: 'Components', title: 'Button', body: 'Five variants × three sizes × danger / icon / loading.' },
  { to: '/components/modal', category: 'Components', title: 'Modal', body: 'Portaled dialog with focus trap and scroll lock.' },
  { to: '/components/toast', category: 'Components', title: 'Toast', body: 'Provider + useToast() hook, four tones, auto-dismiss.' },
  { to: '/playground', category: 'Demo', title: 'Playground', body: 'Prompt → UI, generated live by Claude from WoT primitives.' },
];

export default function Introduction() {
  const { data } = useRepo();

  return (
    <AppShell sidebar={false}>
      {/* ───────── Hero ───────── */}
      <section className={styles.hero}>
        <div className={styles.heroInner}>
          <Link to="/playground" className={styles.pill}>
            <span className={styles.pillDot} aria-hidden />
            New — prompt-to-UI playground, powered by Claude
            <span className={styles.pillArrow}>→</span>
          </Link>

          <h1 className={styles.headline}>
            The foundation for the<br />
            <span className={styles.headlineAccent}>WorldOfTaxonomy</span> interface.
          </h1>

          <p className={styles.subtitle}>
            A working design system that humans, developers, and AI agents read
            from the same source of truth. Tokens are CSS variables, components
            are real React, and the docs are generated by the code that ships.
          </p>

          <div className={styles.ctaRow}>
            <Link to="/components/button" className={styles.ctaPrimary}>Browse components</Link>
            <a
              className={styles.ctaGhost}
              href="https://github.com/aleemcolaberry/worldoftaxonomy-design-system"
              target="_blank"
              rel="noreferrer"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
                <path d="M12 .5C5.7.5.5 5.7.5 12c0 5.1 3.3 9.4 7.8 10.9.6.1.8-.2.8-.6v-2c-3.2.7-3.9-1.4-3.9-1.4-.5-1.3-1.3-1.7-1.3-1.7-1.1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1 1.8 2.7 1.3 3.4 1 .1-.8.4-1.3.7-1.6-2.6-.3-5.3-1.3-5.3-5.8 0-1.3.5-2.3 1.2-3.2-.1-.3-.5-1.5.1-3.1 0 0 1-.3 3.3 1.2 1-.3 2-.4 3-.4s2 .1 3 .4c2.3-1.5 3.3-1.2 3.3-1.2.6 1.6.2 2.8.1 3.1.7.9 1.2 1.9 1.2 3.2 0 4.5-2.7 5.5-5.3 5.8.4.3.8 1 .8 2v3c0 .3.2.7.8.6 4.5-1.5 7.8-5.8 7.8-10.9C23.5 5.7 18.3.5 12 .5z" />
              </svg>
              Star on GitHub
              {data && <span className={styles.ghCount}>{formatCount(data.stars)}</span>}
            </a>
          </div>
        </div>
      </section>

      <div className={styles.container}>
        {/* ───────── Repo strip ───────── */}
        <section className={styles.repoSection}>
          <div className={styles.sectionLabel}>From the repository</div>
          <RepoStats />
        </section>

        {/* ───────── Component mosaic ───────── */}
        <section className={styles.mosaicSection}>
          <div className={styles.sectionLabel}>Built from WoT primitives</div>
          <div className={styles.mosaic}>
            {/* Stat card */}
            <Card className={styles.tileStat} accent>
              <CardBody>
                <span className={styles.statLabel}>Nodes synced</span>
                <span className={styles.statNumber}>1,284</span>
                <Notice tone="success" title="+128 this week" />
              </CardBody>
            </Card>

            {/* Settings form */}
            <Card className={styles.tileForm}>
              <CardHeader><CardTitle>Notification settings</CardTitle></CardHeader>
              <CardBody>
                <div className={styles.formStack}>
                  <Select
                    label="Delivery channel"
                    options={[
                      { value: 'email', label: 'Email' },
                      { value: 'inapp', label: 'In-app' },
                      { value: 'sms', label: 'SMS' },
                    ]}
                    defaultValue="email"
                    size="sm"
                  />
                  <RadioGroup name="freq" defaultValue="daily" orientation="vertical">
                    <Radio value="realtime" label="Real-time" />
                    <Radio value="daily" label="Daily digest" />
                    <Radio value="weekly" label="Weekly digest" />
                  </RadioGroup>
                  <Checkbox label="Mentions" defaultChecked />
                  <Checkbox label="System alerts" />
                </div>
              </CardBody>
              <CardFooter>
                <Btn variant="default" size="sm">Cancel</Btn>
                <Btn variant="primary" size="sm">Save</Btn>
              </CardFooter>
            </Card>

            {/* Search + buttons */}
            <Card className={styles.tileSearch}>
              <CardBody>
                <Input
                  placeholder="Search the taxonomy…"
                  prefix={
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                         strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden>
                      <circle cx="11" cy="11" r="7" /><path d="m21 21-4.3-4.3" />
                    </svg>
                  }
                />
                <div className={styles.btnRow}>
                  <Group>
                    <Btn variant="primary" size="sm">Primary</Btn>
                    <Btn variant="default" size="sm">Default</Btn>
                    <Btn variant="dashed" size="sm">Dashed</Btn>
                  </Group>
                </div>
              </CardBody>
            </Card>

            {/* Notifications */}
            <Card className={styles.tileNotif}>
              <CardHeader><CardTitle>Activity</CardTitle></CardHeader>
              <CardBody>
                <div className={styles.notifStack}>
                  <Notice tone="info" title="Indexing complete" body="1,284 nodes synced." />
                  <Notice tone="warning" title="Stale data" body="Refresh to see latest." />
                  <Notice tone="error" title="Sync failed" body="Retrying in 12 s." />
                </div>
              </CardBody>
            </Card>
          </div>
        </section>

        {/* ───────── Featured ───────── */}
        <section className={styles.featuredSection}>
          <div className={styles.sectionLabel}>Explore</div>
          <div className={styles.grid}>
            {featured.map((f) => (
              <Link key={f.to} to={f.to} className={styles.card}>
                <span className={styles.cardCategory}>{f.category}</span>
                <h3 className={styles.cardTitle}>{f.title}</h3>
                <p className={styles.cardBody}>{f.body}</p>
                <span className={styles.cardArrow}>→</span>
              </Link>
            ))}
          </div>
        </section>

        {/* ───────── Closing CTA ───────── */}
        <section className={styles.closing}>
          <h2 className={styles.closingTitle}>Make it your own.</h2>
          <p className={styles.closingBody}>
            Fork the repo, swap the tokens, ship your brand. Everything here is
            open code — no black boxes, no runtime lock-in.
          </p>
          <Group>
            <a className={styles.ctaPrimary} href="https://github.com/aleemcolaberry/worldoftaxonomy-design-system" target="_blank" rel="noreferrer">
              Get the code
            </a>
            <Link to="/colors/brand" className={styles.ctaGhost}>See the tokens</Link>
          </Group>
        </section>
      </div>
    </AppShell>
  );
}
