import { Link } from 'react-router-dom';
import AppShell from '../../components/AppShell/AppShell';
import PageIntro from '../../components/PageIntro/PageIntro';
import CodeBlock from '../../components/CodeBlock/CodeBlock';
import Btn from '../../components/Button/Button';
import styles from './Introduction.module.css';

interface Feature {
  to: string;
  title: string;
  body: string;
  category: string;
}

const featured: Feature[] = [
  { to: '/colors/palettes', category: 'Foundations', title: 'Color', body: 'Cyan as the only brand accent; Zinc for every neutral; muted scales for state.' },
  { to: '/typography/font-family', category: 'Foundations', title: 'Typography', body: 'Geist + Geist Mono — variable woff2, OFL-1.1 licensed, bundled in /public/fonts.' },
  { to: '/components/button', category: 'Components', title: 'Button', body: 'Five variants × three sizes × danger / icon-only / loading. The flagship primitive.' },
  { to: '/playground', category: 'Demo', title: 'Playground', body: 'Prompt-to-UI demo — type a brief, watch WoT components compose into the brief.' },
];

export default function Introduction() {
  return (
    <AppShell>
      <PageIntro
        eyebrow="Getting Started"
        title="Introduction"
        lede="WoT AI Design System turns your design system into an executable UI language — humans, developers, and AI coding agents read from the same source of truth."
      />

      <section className={styles.section}>
        <h2 className={styles.h2}>What this is</h2>
        <p className={styles.body}>
          A working React + TypeScript design system. Tokens are CSS variables.
          Components are real React with full prop APIs. Documentation is in this
          site itself, generated by the same code that ships to your app — so
          docs and reality can&apos;t drift.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.h2}>Try it</h2>
        <p className={styles.body}>Clone, install, run.</p>
        <CodeBlock
          language="bash"
          code={`git clone https://github.com/aleemcolaberry/worldoftaxonomy-design-system.git
cd worldoftaxonomy-design-system
npm install
npm run dev`}
        />
        <div className={styles.cta}>
          <Link to="/components/button" className={styles.ctaPrimary}>
            <Btn variant="primary" size="md">Browse components →</Btn>
          </Link>
          <Link to="/playground" className={styles.ctaSecondary}>
            <Btn variant="default" size="md">Open playground</Btn>
          </Link>
        </div>
      </section>

      <section className={styles.section}>
        <h2 className={styles.h2}>Featured</h2>
        <div className={styles.grid}>
          {featured.map((f) => (
            <Link key={f.to} to={f.to} className={styles.card}>
              <span className={styles.cardCategory}>{f.category}</span>
              <h3 className={styles.cardTitle}>{f.title}</h3>
              <p className={styles.cardBody}>{f.body}</p>
              <span className={styles.cardArrow}>→</span>
            </Link>
          ))}
        </div>
      </section>

      <section className={styles.section}>
        <h2 className={styles.h2}>Three-layer architecture</h2>
        <p className={styles.body}>
          The same artefact in three guises: a Figma source of truth, a
          developer-consumable component library, and a machine-readable
          contract for AI coding agents.
        </p>
        <img
          src="/images/executable-ui-language.png"
          alt="WoT AI Design System — the executable UI language"
          className={styles.figure}
        />
      </section>
    </AppShell>
  );
}
